// Official barangays of San Juan, La Union for the property form's area select.
// The DB column stays free `text`; this just drives the dropdown options.
export const SAN_JUAN_AREAS = [
  "Allangigan",
  "Aludaid",
  "Bacsayan",
  "Balballosa",
  "Bambanay",
  "Bugbugcao",
  "Caarusipan",
  "Cabaroan",
  "Cabugnayan",
  "Cacapian",
  "Caculangan",
  "Calincamasan",
  "Casilagan",
  "Catdongan",
  "Dangdangla",
  "Dasay",
  "Dinanum",
  "Duplas",
  "Guinguinabang",
  "Ili Norte (Poblacion)",
  "Ili Sur (Poblacion)",
  "Legleg",
  "Lubing",
  "Nadsaag",
  "Nagsabaran",
  "Naguirangan",
  "Naguituban",
  "Nagyubuyuban",
  "Oaquing",
  "Pacpacac",
  "Pagdildilan",
  "Panicsican",
  "Quidem",
  "San Felipe",
  "Santa Rosa",
  "Santo Rosario",
  "Saracat",
  "Sinapangan",
  "Taboc",
  "Talogtog",
  "Urbiztondo",
] as const;

export type SanJuanArea = (typeof SAN_JUAN_AREAS)[number];
